#!/bin/bash
while [ "$1" != "" ]
do
	case $1 in
		wpa) echo "Enter passphrase for ssid $2" ;wpa_passphrase "$2" > /tmp/wpa ; wpa_supplicant -B -D wext -i wlan0 -c /tmp/wpa ;;
		wep) echo "Enter passphrase for ssid $2" ; read pass ;iw dev wlan0 connect "$2" key 0:"$pass";;
		kill) for p in run-at-boot wifite.py broadcast-keys airodump-ng aireplay-ng ; do pkill $p ; done;;
	esac
	shift
done
