#!/bin/bash
while [ "$1" != "" ]
do
	case $1 in
		wpa) echo "Enter passphrase for ssid $2" ;wpa_passphrase "$2" > /tmp/wpa ; wpa_supplicant -B -D wext -i wlan0 -c /tmp/wpa ; dhclient -1 wlan0 ;;
		wep) read -p "Enter passphrase for ssid $2" -s pass ;ifconfig wlan0 up;iw dev wlan0 connect "$2" key 0:"$pass";dhclient -1 wlan0;;
		kill) for p in run-at-boot wifite.py broadcast-keys airodump-ng aireplay-ng ; do pkill $p ; done;;
	esac
	shift
done
