#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
export HOME=/root
if [ ! ifconfig -a wlan0 >/dev/null ]
then
	echo 'wlan0 not found'
	exit 1
fi
cd /root
while true ; do /root/bin/wifite.py --wep --all >/tmp/wifite.log ; done &
/root/kocrack/broadcast-keys
